name: test-weather-data-scraper
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test-weather-data-scraper:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.11'
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: Install required python packages
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pytest coverage
      - name: Run pytest
        run: |
          coverage run -m pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3